sudo: required
dist: trusty
addons:
  apt:
    packages:
    - nodejs
    - npm
services:
  - docker
install:
  - npm install -g dockerfile_lint
before_script:
  - dockerfile_lint  -f Dockerfile
  - docker pull centos:7
script:
  - docker build --tag garethahealy/centos-pod-pause .
